// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
)

type Album struct {
	ID     uuid.UUID
	Title  string
	Artist string
	Price  string
}
