name: Failing Test
description: Report continuously failing tests or jobs
labels: ["failing-test", "needs-triage"]
assignees: "sarvsav"

body:
  - type: textarea
    id: tests
    attributes:
      label: Which tests are failing?
    validations:
      required: true

  - type: textarea
    id: since
    attributes:
      label: Since when has it been failing?
    validations:
      required: true
