#!/usr/bin/env bash

## Create data directory for buildbuddy
function create_data_dir() {
  echo "Creating data directory for buildbuddy: $HOME/opt/buildbuddy/data"
  if [ ! -d "$HOME/opt/buildbuddy/data" ]; then
    mkdir -p "$HOME/opt/buildbuddy/data"
  fi
}

## Create config file for buildbuddy
function create_config_file() {
  echo "Creating config file for buildbuddy: $HOME/etc/buildbuddy/config.yaml"
  if [ ! -f "$HOME/etc/buildbuddy/config.yaml" ]; then
    cat > "$HOME/etc/buildbuddy/config.yaml" <<EOF
# DO NOT EDIT: BuildBuddy configuration file
# This file is automatically generated by the buildbuddy.sh script.
# To change configuration options, edit the buildbuddy.sh script.
app:
  build_buddy_url: "http://localhost:8080"
database:
  data_source: "sqlite3:///data/buildbuddy.db"
storage:
  ttl_seconds: 86400 # One day in seconds.
  chunk_file_size_bytes: 3000000 # 3 MB
  disk:
    root_directory: /data/buildbuddy
cache:
  max_size_bytes: 10000000000 # 10 GB
  disk:
    root_directory: /data/buildbuddy-cache
EOF
    fi
}

## Run buildbuddy using docker
function run_buildbuddy() {
  echo "Running buildbuddy using docker"
  docker run --publish 1985:1985 \
             --publish 8080:8080 \
             --name buildbuddy \
             --rm \
             --volume "$HOME/etc/buildbuddy/config.yaml:/config.yaml" \
             --volume "$HOME/opt/buildbuddy/data":/data \
             gcr.io/flame-public/buildbuddy-app-onprem:latest

}