name: Auto Assign Issue

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Issue
      uses: pozil/auto-assign-issue@b787bcda4fa1620522e73e7a5fe0f3b57b03b6ad # v2.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: sarvsav # Replace 'username' with the GitHub username of the user you want to assign the issue to
        allowSelfAssign: false
