name: Auto Assign Issue

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Issue
      uses: pozil/auto-assign-issue@c5bca5027e680b9e8411b826d16947afd8c76b32 # v2.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: sarvsav # Replace 'username' with the GitHub username of the user you want to assign the issue to
        allowSelfAssign: false
