name: Auto Assign Issue

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Issue
      uses: pozil/auto-assign-issue@39c06395cbac76e79afc4ad4e5c5c6db6ecfdd2e # v2.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: sarvsav # Replace 'username' with the GitHub username of the user you want to assign the issue to
        allowSelfAssign: false
