name: Auto Assign Issue

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Issue
      uses: pozil/auto-assign-issue@c015a6a3f410f12f58255c3d085fd774312f7a2f # v2.1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: sarvsav # Replace 'username' with the GitHub username of the user you want to assign the issue to
        allowSelfAssign: false
