name: Collect Repository Stats
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  j1:
    if: github.repository == 'sarvsav/go-starter-template'
    name: repostats-for-project
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: sarvsav/go-starter-template
          ghtoken: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
